version: '3.3'
services:
  jupyter:
    image: jupyter/pyspark-notebook
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    ports:
      - "8888:8888"
    restart: always
